
[general]
github_base_branch = "main"

[models]
doc_manager_agent = "gemini-2.5-pro-preview-05-06"
qa_agent = "gemini-2.5-pro-preview-05-06"
generation_agent = "gemini-2.5-pro-preview-05-06"
evaluation_agent = "gemini-2.5-pro-preview-05-06"

[github_tool_settings]
commit_message_prefix = "AI Doc Agent: "
